#
# Docker Compose file for a software version
# of a Gateway.
#

name: "ctxd"

include:
  - ./config-zone2.yml
  
services:

  #
  # Gateway
  #
  import_diode:
    image:  ghcr.io/configuredthings/ctxd_diode:${ctxd_version}
    hostname: import.gateway.zone2.ctxd
    networks:
      ctxd_low:
        aliases:
          - gateway.low.zone2.ctxd
      ctxd_high:
    configs:
      - source: import_diode
        target: /opt/ct/config/diode.sfjs
      - source: status_high
        target: /opt/ct/system/config/status.sfjs
    
          
  export_diode:
    image:  ghcr.io/configuredthings/ctxd_diode:${ctxd_version}
    hostname: export.gateway.zone2.ctxd
    networks:
      ctxd_high:
        aliases:
          - gateway.high.zone2.ctxd
      ctxd_low:     
    configs:
      - source: export_diode
        target: /opt/ct/config/diode.sfjs
      - source: status_high
        target: /opt/ct/system/config/status.sfjs

networks:
  ctxd_low:
    name: ctxd_low_1
  ctxd_high:
    name: ctxd_high_1
  



