#
# Docker Compose file for the Console
#   
name: ctxd-ops

secrets:
  git:
    file: ../../secrets/ops/console/ct-admin/git    
  user:
    file: ../../secrets/ops/console/ct-admin/password

services:

  console:
    image: ghcr.io/configuredthings/sfjs-console:${console_version}
    hostname: console.ops.ctxd
    environment:
      - SFJS_CONSOLE_PORT=${console_port}
    ports:
      - ${console_port}:80
    volumes:
      - ../../volumes/ops/console/ct-admin/certs:/opt/ct/gui/certs
      - ../../volumes/ops/console/ct-admin/config/settings.sfjs:/opt/ct/gui/settings.sfjs
      - ../../volumes/ops/console/ct-admin/config/git.sfjs:/opt/ct/gui/git.sfjs
      - ../../volumes/ops/console/ct-admin/config/user.sfjs:/opt/ct/gui/user.sfjs
    secrets:
      - git
      - user
    networks:
      - ctxd_ops

networks:
  ctxd_ops:
    name: ctxd_ops


