#
# Docker Compose file for the Status and Console Components
#   
#
name: ctxd-ops

secrets:
  git:
    file: ../../secrets/ops/console/ct-admin/git    
  user:
    file: ../../secrets/ops/console/ct-admin/password

services:

  status:
    extends: 
      file: ./status.yml
      service: status
    
  console:
    extends: 
      file: ./console.yml
      service: console
    
networks:
  ctxd_high:
    name: ctxd_high


