#
# Docker Compose file for the Status Service
#   
#
name: ctxd-ops

configs:
  # Config details for an external git webhook server  
  # ext_webhook:
  #   content: |
  #     {
  #       host: "gwhg.service.trade.configuredthings.com",
  #     }

services:

  status:
    image: ghcr.io/configuredthings/ctxd_ops_status:2.13.4
    hostname: status.ops.ctxd
    ports:
      - 32001:32001
      - 32002:32002
      - 32003:32003
      - 32004:32004
      - 32005:32005
    #configs:
    #  - source: ext_webhook
    #    target: /opt/ct/config/ext_webhook.sfjs
    volumes:
      - ../../volumes/ops/status/certs:/opt/ct/config/certs
      - ../../volumes/ops/status/ext_certs:/opt/ct/config/ext_certs
    networks:
      ctxd_ops:
        aliases:
          - status.ops.ctxd
          - alerts.ops.ctxd
          - gitwh.ops.ctxd
    
networks:
  ctxd_ops:
    name: ctxd_ops


