name: "ctxd-zone2"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
include:
  - ../high/config-zone2.yml
  - ../gateway/config-zone2.yml
  - ../low/config-zone2.yml

#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    

#
# List of Dockers
#
services:

  high_mqtt:
    extends: 
      file: ../high/zone2.yml
      service: high_mqtt
    image: ctxd_high_mqtt:${ctxd_version}
      
  high_import:
    extends:
      file: ../high/zone2.yml
      service: high_import
    image: ctxd_high_import:${ctxd_version}
      
  high_export:
    extends:
      file: ../high/zone2.yml
      service: high_export
    image: ctxd_high_export:${ctxd_version}
    
  import_diode:
    extends: 
      file: ../gateway/zone2.yml
      service: import_diode
    image: ctxd_diode:${ctxd_version}
          
  export_diode:
    extends: 
      file: ../gateway/zone2.yml
      service: export_diode
    image: ctxd_diode:${ctxd_version}
  
  low_mqtt:
    extends: 
      file: ../low/zone2.yml
      service: low_mqtt
    image: ctxd_low_mqtt:${ctxd_version}
      
  low_import:
    extends:
      file: ../low/zone2.yml
      service: low_import
    image: ctxd_low_import:${ctxd_version}

  low_export:
    extends:
      file: ../low/zone2.yml
      service: low_export
    image: ctxd_low_export:${ctxd_version}

  low_emulators:
    extends:
      file: ../low/zone2.yml
      service: low_emulators
    image: ctxd_low_emulators:${ctxd_version}

networks:
  ctxd_low:
    name: ctxd_low_1
  ctxd_high:
    name: ctxd_high_1
  ctxd_ops:
    name: ctxd_ops
    
