name: "ctxd"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode.
#
# This adds additional mount points to each service
# defined in docker-compose-mono-local to support
# development inside the containers 
#
# env var XD_DEV? must be set to point to a clone of
# the source repo of CrossDomainDocker
# 
configs:

  zone:
    content: |
      {
        zone: 'Zone1'
      }
  
  # High side of the Gateway (i.e. to Low domain)
  gateway_high:
    content: |
      {
        host: "gateway.high.ctxd",
        port: 80,
        protocol: http,
      }

  # High Side Import Web Server
  import_high:
    content: |
      {
        host: "import.high.ctxd",
        port: 80,
        protocol: http,
      }

  # Low Side Export Web Server
  export_high:
    content: |
      {
        host: "export.high.ctxd",
        port: 80,
        protocol: http,
      }
    
  # High Side Ops Status Server
  status_ops:
    content: |
      {
        remote: {
          protocol: https,
          host: "status.ops.ctxd", 
          port: 32001, 
          channel: "ctxdStatus"
        }
      }

  # High Side Import Status Server
  status_high:
    content: |
      {
        remote: {
          host: "status.high.ctxd", 
          port: 7776, 
          channel: "ct-status"
        }
      }

  # External High Side MQTT server
  mqtt_high:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.high.ctxd",
          port:     1883,
          format:   json
      }

  # Alert targets    
  alerts_high:
    content: |
      {
        console: {enabled: true},
        slack:   {enabled: false},
        mqtt:    {enabled: true},
      }

  # Thingsboard (Metrics)
  thingsboard_high:
    content: |
      {enabled: false, host: null, port: null, protocol:http}


  # Pipeline Telemetry
  stats_high:
    content: |
      {
        thingsboard: {enabled: false}
      }    

  # Low side of the Gateway (i.e. to High domain)
  gateway_low:
    content: |
      {
        host: "gateway.low.ctxd",
        port: 80,
        protocol: http,
      }

  
  # External Low Side MQTT server
  mqtt_low:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.low.ctxd",
          port:     1883,
          format:   json
      }

  # Low Side Export Web Server
  export_low:
    content: |
      {
        host: "export.low.ctxd",
        port: 80,
        protocol: http,
      }

  # MM to connect to for configuration
  config_low:
    content: |
      {
        host: "config.low.ctxd",
        port: 22000,
        protocol: http,
        channel: 'application',
      }

  # MM to send status to
  status_low:
    content: |
      {
        remote: {
          host: "status.low.ctxd", 
          port: 7776, 
          channel: "ct-status"
        }
      }
    
  # Import Diode Config
  import_diode:
    content: |
      {  
        input:  {host: 'gateway.low.ctxd'},
        routes: {
          default: 'http://import.high.ctxd:80/files'
        }
      }

  # Export Diode Config
  export_diode:
    content: |
      {  
        input:  {host: 'gateway.high.ctxd'},
        routes: {
          default: 'http://export.low.ctxd:80/files'
        }
      }

#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    
  slack:
    file: ../../secrets/high/slack    

#
# List of Dockers
#     
services:
  high_mqtt:
    extends: 
      file: ./mono-zone1-local.yml
      service: high_mqtt
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_mqtt/config/mqtt/mqtt.conf:/etc/mosquitto/mosquitto.conf
      
  high_import:
    extends:
      file: ./mono-zone1-local.yml
      service: high_import
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_import/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/high/high_base/config/init-config/high-config.sfjs:/opt/ct/init-config/high-config.sfjs
      - ${XD_DEV?}/images/high/high_base/config/init-config/high-config-local.sfjs:/opt/ct/init-config/high-config-local.sfjs
      - ${XD_DEV?}/images/high/high_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/high/high_base/sfjs/PipelineStatus.sfjx:/opt/ct/init/PipelineStatus.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/Alerts.sfjx:/opt/ct/init/Alerts.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/Config.sfjx:/opt/ct/init/Config.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/ImportPipelines.sfjx:/opt/ct/init/ImportPipelines.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/Local.sfjx:/opt/ct/init/Local.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/SfjsAck.sfjx:/opt/ct/init/SfjsAck.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/Stats.sfjx:/opt/ct/init/Stats.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/Status.sfjx:/opt/ct/init/Status.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/WebServer.sfjx:/opt/ct/init/WebServer.sfjx
      - ${XD_DEV?}/images/high/high_import/sfjs/High_Import.sfjs:/opt/ct/init/High_Import.sfjs
  
  high_export:
    extends:
      file: ./mono-zone1-local.yml
      service: high_export
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_base/config/init-config/high-config.sfjs:/opt/ct/init-config/high-config.sfjs
      - ${XD_DEV?}/images/high/high_base/config/init-config/high-config-local.sfjs:/opt/ct/init-config/high-config-local.sfjs
      - ${XD_DEV?}/images/high/high_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/high/high_base/sfjs/Alerts.sfjx:/opt/ct/init/Alerts.sfjx
      - ${XD_DEV?}/images/high/high_base/sfjs/PipelineStatus.sfjx:/opt/ct/init/PipelineStatus.sfjx
      - ${XD_DEV?}/images/high/high_export/sfjs/Config.sfjx:/opt/ct/init/Config.sfjx
      - ${XD_DEV?}/images/high/high_export/sfjs/ExportPipelines.sfjx:/opt/ct/init/ExportPipelines.sfjx
      - ${XD_DEV?}/images/high/high_export/sfjs/GitConfig.sfjx:/opt/ct/init/GitConfig.sfjx
      - ${XD_DEV?}/images/high/high_export/sfjs/Local.sfjx:/opt/ct/init/Local.sfjx
      - ${XD_DEV?}/images/high/high_export/sfjs/High_Export.sfjs:/opt/ct/init/High_Export.sfjs
  
  import_diode:
    extends: 
      file: ./mono-zone1-local.yml
      service: import_diode
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/gateway/diode/sfjs:/opt/ct/init
              
  export_diode:
    extends: 
      file: ./mono-zone1-local.yml
      service: export_diode
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/gateway/diode/sfjs:/opt/ct/init
      
  low_mqtt:
    extends: 
      file: ./mono-zone1-local.yml
      service: low_mqtt
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_mqtt/config/mqtt/mqtt.conf:/etc/mosquitto/mosquitto.conf
      
  low_import:
    extends:
      file: ./mono-zone1-local.yml
      service: low_import
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/low/low_base/sfjs/Alerts.sfjx:/opt/ct/init/Alerts.sfjx
      - ${XD_DEV?}/images/low/low_base/sfjs/PipelineStatus.sfjx:/opt/ct/init/PipelineStatus.sfjx
      - ${XD_DEV?}/images/low/low_import/sfjs/Config.sfjx:/opt/ct/init/Config.sfjx
      - ${XD_DEV?}/images/low/low_import/sfjs/ImportPipelines.sfjx:/opt/ct/init/ImportPipelines.sfjx
      - ${XD_DEV?}/images/low/low_import/sfjs/Local.sfjx:/opt/ct/init/Local.sfjx
      - ${XD_DEV?}/images/low/low_import/sfjs/MQTT_Monitor.sfjx:/opt/ct/init/MQTT_Monitor.sfjx
      - ${XD_DEV?}/images/low/low_import/sfjs/Low_Import.sfjs:/opt/ct/init/Low_Import.sfjs

  low_export:
    extends:
      file: ./mono-zone1-local.yml
      service: low_export
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/low/low_base/sfjs/Alerts.sfjx:/opt/ct/init/Alerts.sfjx
      - ${XD_DEV?}/images/low/low_base/sfjs/PipelineStatus.sfjx:/opt/ct/init/PipelineStatus.sfjx
      - ${XD_DEV?}/images/low/low_export/sfjs/Config.sfjx:/opt/ct/init/Config.sfjx
      - ${XD_DEV?}/images/low/low_export/sfjs/ExportPipelines.sfjx:/opt/ct/init/ExportPipelines.sfjx
      - ${XD_DEV?}/images/low/low_export/sfjs/Local.sfjx:/opt/ct/init/Local.sfjx
      - ${XD_DEV?}/images/low/low_export/sfjs/WebServer.sfjx:/opt/ct/init/WebServer.sfjx
      - ${XD_DEV?}/images/low/low_export/sfjs/Low_Export.sfjs:/opt/ct/init/Low_Export.sfjs

  low_emulators:
    extends:
      file: ./mono-zone1-local.yml
      service: low_emulators
    volumes:
      - ${XD_DEV?}/src:/opt/ct/src
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/init-config/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/sfjs/Alerts.sfjx:/opt/ct/init/Alerts.sfjx
      - ${XD_DEV?}/images/low/low_base/sfjs/PipelineStatus.sfjx:/opt/ct/init/PipelineStatus.sfjx
      - ${XD_DEV?}/images/low/low_emulators/sfjs/Local.sfjx:/opt/ct/init/Local.sfjx
      - ${XD_DEV?}/images/low/low_emulators/sfjs/Low_Emulators.sfjs:/opt/ct/init/Low_Emulators.sfjs

networks:
  ctxd_low:
    name: ctxd_low
  ctxd_high:
    name: ctxd_high
  ctxd_ops:
    name: ctxd_ops
    
