#
# Docker Compose file for the Status and Console Components
#   
#
name: ctxd-ops

configs:
  # Config details for an external git webhook server  
  ext_webhook:
    content: |
      {
        host: "gwhg.service.trade.configuredthings.com",
      }

secrets:
  git:
    file: ../../secrets/ops/console/ct-admin/git    
  user:
    file: ../../secrets/ops/console/ct-admin/password

services:

  status:
    extends: 
      file: ../ops/ops.yml
      service: status
    image: ctxd_ops_status:2.13.0

  console:
    extends: 
      file: ../ops/ops.yml
      service: console
    image: sfjs-console:2.32.0
    volumes:
      - ../../volumes/ops/console/ct-admin/git-zones.sfjs:/opt/ct/gui/git.sfjs
  
networks:
  ctxd_ops:
    name: ctxd_ops

