configs:

  mqtt_low:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.low.ctxd",
          port:     1883,
          format:   json
      }

  mosquitto_low:
    content: |
      listener 1883
      allow_anonymous true
      sys_interval 0 