#
# Docker Compose file for the Low Domain Services
#

name: "ctxd-low"

include:
  - ./config.yml
 
services:

  #
  # Low Domain Import Service
  #    
  low_import:
    image: ghcr.io/configuredthings/ctxd_low_import:${ctxd_version}
    hostname: import.low.ctxd
    networks:
      ctxd_low:
        aliases:
          - status.low.ctxd
    configs:
      - source: mqtt_low
        target: /opt/ct/integrations/mqtt.sfjs       
    
  #
  # Low Domain Export Service
  #  
  low_export:
    image:  ghcr.io/configuredthings/ctxd_low_export:${ctxd_version}
    hostname: export.low.ctxd
    networks:
      ctxd_low:
        aliases:
          - config.low.ctxd
      
  #
  # Low Domain MQTT Service
  #
  low_mqtt:
    image: ghcr.io/configuredthings/ctxd_low_mqtt:${ctxd_version}
    hostname: mqtt.low.ctxd
    ports:
      - 21883:1883
    networks:
      - ctxd_low
    
networks:
  ctxd_low:
    name: ctxd_low



