name: "ctxd-1"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
include:
  - ./config-zone1.yml

  
services:

  low_import:
    image: ghcr.io/configuredthings/ctxd_low:${ctxd_version}
    hostname: import.low.zone1.ctxd
    environment:
      - CT_INIT_DIR=/opt/ct/init/import  
    networks:
      ctxd_low:
        aliases:
          - status.low.zone1.ctxd
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: gateway_low
        target: /opt/ct/config/gateway.sfjs    
      - source: config_low
        target: /opt/ct/config/config.sfjs
      - source: mqtt_low
        target: /opt/ct/integrations/mqtt.sfjs       
     

  low_export:
    image:  ghcr.io/configuredthings/ctxd_low:${ctxd_version}
    hostname: export.low.zone1.ctxd  
    environment:
      - CT_INIT_DIR=/opt/ct/init/export  
    networks:
      ctxd_low:
        aliases:
        - config.low.zone1.ctxd
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs  
      - source: gateway_low
        target: /opt/ct/config/gateway.sfjs    

  low_mqtt:
    image: eclipse-mosquitto:alpine
    hostname: mqtt.low.zone1.ctxd  
    ports:
      - 21883:1883
    networks:
      - ctxd_low
    configs:
      - source: mosquitto_low
        target: /mosquitto/config/mosquitto.conf   

  low_emulators:
    image:  ghcr.io/configuredthings/ctxd_emulators:${ctxd_version}
    hostname: emulators.low.zone1.ctxd  
    networks:
      - ctxd_low
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: em_status_low
        target: /opt/ct/system/config/status.sfjs  
      - source: em_config_low
        target: /opt/ct/config/config.sfjs  
      - source: mqtt_low
        target: /opt/ct/integrations/mqtt.sfjs  
      

networks:
  ctxd_low:
    name: ctxd_low_1
    
