name: "ctxd-1"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
configs:

  zone:
    content: |
      {
        zone: 'Zone1'
      }

  # Low side of the Gateway (i.e. to High domain)
  gateway_low:
    content: |
      {
        host: "gateway.low.ctxd",
        port: 80,
        protocol: http,
      }

  # Low Side Export Web Server
  export_low:
    content: |
      {
        host: "export.low.ctxd",
        port: 80,
        protocol: http,
      }
    
  # External MQTT server
  mqtt_low:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.low.ctxd",
          port:     1883,
          format:   json
      }

  # MM to connect to for configuration
  config_low:
    content: |
      {
        host: "config.low.ctxd",
        port: 22000,
        protocol: http,
        channel: 'application',
      }

  # MM to send status to
  status_low:
    content: |
      {
        remote: {
          host: "status.low.ctxd", 
          port: 7776, 
          channel: "ct-status"
        }
      }
    
  
services:

  low_import:
    extends:
      file: ./ctxd.yml
      service: low_import
    hostname: import.low.zone1.ctxd  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs  

  low_export:
    extends:
      file: ./ctxd.yml
      service: low_export
    hostname: export.low.zone1.ctxd  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs  

  low_mqtt:
    extends: 
      file: ./ctxd.yml
      service: low_mqtt
    hostname: mqtt.low.zone1.ctxd  
      
  low_emulators:
    extends:
      file: ./emulators.yml
      service: low_emulators
    hostname: emulators.low.zone1.ctxd  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs  

networks:
  ctxd_low:
    name: ctxd_low_1
    
