name: "ctxd"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode.
#
# This adds additional mount points to each service
# defined in docker-compose-mono-local to support
# development inside the containers 
#
# env var XD_DEV? must be set to point to a clone of
# the source repo of CrossDomainDocker
# 
configs:

  # High side of the Gateway (i.e. to Low domain)
  gateway_high:
    content: |
      {
        host: "gateway.high.ctxd",
        port: 80,
        protocol: http,
      }

  # High Side Import Web Server
  import_high:
    content: |
      {
        host: "import.high.ctxd",
        port: 80,
        protocol: http,
      }

  # Low Side Export Web Server
  export_high:
    content: |
      {
        host: "export.high.ctxd",
        port: 80,
        protocol: http,
      }
    
  # High Side Import Status Server
  status_high:
    content: |
      {
        status: {
          remote: {
            host: "import.high.ctxd", 
            port: 7776, 
            channel: "ct-status"
          }
        }
      }

  # External High Side MQTT server
  mqtt_high:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.high.ctxd",
          port:     1883,
          format:   json
      }

  # Alert targets    
  alerts_high:
    content: |
      {
        console: {enabled: true},
        slack:   {enabled: false},
        mqtt:    {enabled: false},
      }

  # Thingsboard (Metrics)
  thingsboard_high:
    content: |
      {enabled: false}

  # Pipeline Telemetry
  stats_high:
    content: |
      {
        thingsboard: {enabled: false}
      }    

  # Low side of the Gateway (i.e. to High domain)
  gateway_low:
    content: |
      {
        host: "gateway.low.ctxd",
        port: 80,
        protocol: http,
      }

  
  # External Low Side MQTT server
  mqtt_low:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.low.ctxd",
          port:     1883,
          format:   json
      }

  # Low Side Export Web Server
  export_low:
    content: |
      {
        host: "export.low.ctxd",
        port: 80,
        protocol: http,
      }

  # Import Diode Config
  import_diode:
    content: |
      {  
        input:  {host: 'gateway.low.ctxd'},
        target: {host: 'import.high.ctxd'}
      }

  # Export Diode Config
  export_diode:
    content: |
      {  
        input:  {host: 'gateway.high.ctxd'},
        target: {host: 'export.low.ctxd'},
      }

#
# List of Dockers
#     
services:

  import_diode:
    extends: 
      file: ./mono-local.yml
      service: import_diode
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/gateway/diode/sfjs:/opt/ct/init
      - ${XD_DEV?}/images/gateway/diode/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
              
  export_diode:
    extends: 
      file: ./mono-local.yml
      service: export_diode
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/gateway/diode/sfjs:/opt/ct/init
      - ${XD_DEV?}/images/gateway/diode/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      
  low_mqtt:
    extends: 
      file: ./mono-local.yml
      service: low_mqtt
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_mqtt/config/mqtt/mqtt.conf:/etc/mosquitto/mosquitto.conf
      
  low_import:
    extends:
      file: ./mono-local.yml
      service: low_import
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/low/low_base/sfjs:/opt/ct/base
      - ${XD_DEV?}/images/low/low_import/sfjs:/opt/ct/init

  low_export:
    extends:
      file: ./mono-local.yml
      service: low_export
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/low/low_base/sfjs:/opt/ct/base
      - ${XD_DEV?}/images/low/low_export/sfjs:/opt/ct/init

  low_emulators:
    extends:
      file: ./mono-local.yml
      service: low_emulators
    volumes:
      - ${XD_DEV?}/src:/opt/ct/src
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config.sfjs:/opt/ct/init-config/low-config.sfjs
      - ${XD_DEV?}/images/low/low_base/config/ct/low-config-local.sfjs:/opt/ct/init-config/low-config-local.sfjs
      - ${XD_DEV?}/images/low/low_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/low/low_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/low/low_emulators/sfjs:/opt/ct/init

  high_mqtt:
    extends: 
      file: ./mono-local.yml
      service: high_mqtt
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/high/high_mqtt/config/mqtt/mqtt.conf:/etc/mosquitto/mosquitto.conf
      
  high_import:
    extends:
      file: ./mono-local.yml
      service: high_import
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_import/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/high/high_base/config/ct/high-config.sfjs:/opt/ct/init-config/high-config.sfjs
      - ${XD_DEV?}/images/high/high_base/config/ct/high-config-local.sfjs:/opt/ct/init-config/high-config-local.sfjs
      - ${XD_DEV?}/images/high/high_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/high/high_import/sfjs:/opt/ct/init
  
  high_export:
    extends:
      file: ./mono-local.yml
      service: high_export
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
      - ${XD_DEV?}/images/high/high_base/config/ct/high-config.sfjs:/opt/ct/init-config/high-config.sfjs
      - ${XD_DEV?}/images/high/high_base/config/ct/high-config-local.sfjs:/opt/ct/init-config/high-config-local.sfjs
      - ${XD_DEV?}/images/high/high_base/templates:/opt/ct/templates
      - ${XD_DEV?}/images/high/high_base/statusSender.sfjs:/opt/ct/system/init/statusSender.sfjs
      - ${XD_DEV?}/images/high/high_export/sfjs:/opt/ct/init
  
networks:
  ctxd_low:
    name: ctxd_low
  ctxd_high:
    name: ctxd_high
    
