configs:

  mqtt_high:
    content: |
      {
        enabled:  true,
        protocol: mqtt,
        host:     "mqtt.high.ctxd",
        port:     1883,
        format:   json
      }

  mosquitto_high:
    content: |
      listener 1883
      allow_anonymous true