# Contains the configuration values for zone 1  
configs:

  zone:
    content: |
      {
        zone: 'Zone2'
      }

  mqtt_high:
    content: |
      {
        enabled:  true,
        protocol: mqtt,
        host:     "mqtt.high.zone2.ctxd",
        port:     1883,
        format:   json
      }

  mosquitto_high:
    content: |
      listener 1883
      allow_anonymous true
      
  gateway_high:
    content: |
      {
        host: "gateway.high.zone2.ctxd",
      }

  import_high:
    content: |
      {
        host: "import.high.zone2.ctxd",
      }    

  config_high:
    content: |
      {
        host: "config.high.zone2.ctxd",
      }