#
# Docker Compose file for the High Domain Services
#

name: "ctxd-high"

include:
  - ./config.yml
  
#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    
  #slack:
  #  file: ../../secrets/high/slack
  
#
# List of Dockers
#
services:

  #
  # High Domain Import Service
  #    
  high_import:
    image:  ghcr.io/configuredthings/ctxd_high_import:${ctxd_version}
    hostname: import.high.ctxd
    networks:
      ctxd_high:
        aliases:
           - status.high.ctxd
      ctxd_ops:    
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs
      - source: mqtt_high
        target: /opt/ct/integrations/mqtt.sfjs    
    volumes:
      - ../../volumes/high/import/certs:/opt/ct/certs
    
  #
  # High Domain Export Service
  #  
  high_export:
    image:  ghcr.io/configuredthings/ctxd_high_export:${ctxd_version}
    hostname: export.high.ctxd
    networks:
      ctxd_high:
        aliases:
          - config.high.ctxd
      ctxd_ops:    
    secrets:
      - git  
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs  
    volumes:
      - ../../volumes/high/export/certs:/opt/ct/certs
      - ../../volumes/high/export/keys:/opt/ct/keys
      - ../../volumes/high/export/git.sfjs:/opt/ct/integrations/git.sfjs
      - ../../volumes/high/export/signingPolicy.sfjs:/opt/ct/config/signingPolicy.sfjs
    
  #
  # High domain MQTT Server
  #
  high_mqtt:
    image:  ghcr.io/configuredthings/ctxd_high_mqtt:${ctxd_version}
    hostname: mqtt.high.ctxd
    ports:
      - 31883:1883
    networks:
      ctxd_high:
        aliases:
          - mqtt.high.ctxd
      ctxd_ops:    
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs
    volumes:
      - ../../volumes/high/mqtt/certs:/opt/ct/certs


networks:
  ctxd_high:
    name: ctxd_high
  ctxd_ops:
    name: ctxd_ops  



