name: "ctxd-2"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
configs:

  zone:
    content: |
      {
        zone: 'Zone2'
      }

# The high side of the Gateway (i.e. to Low domain)
  gateway_high:
    content: |
      {
        host: "gateway.high.ctxd",
        port: 80,
        protocol: http,
      }

  # High Side Import Web Server
  import_high:
    content: |
      {
        host: "import.high.ctxd",
        port: 80,
        protocol: http,
      }
    
  # High Side Ops Status Server
  status_ops:
    content: |
      {
        remote: {
          protocol: https,
          host: "status.ops.ctxd", 
          port: 32001, 
          channel: "ctxdStatus"
        }
      }

  # External MQTT server
  mqtt_high:
    content: |
      {
        enabled:  true,
        protocol: mqtt,
        host:     "mqtt.high.ctxd",
        port:     1883,
        format:   json
      }

  # Alert targets
  #
  # Defaults
  #   {
  #     console: {enabled: true},
  #     slack:   {enabled: false}
  #     mqtt:    {enabled: false, protocol: mqtt, host: "mqtt.high.ctxd", port: 1883},    
  #   }
  #
  # If enabling slack as an alert target then you also need to uncomment
  # the slack secrets entries in 'secrets' and 'services.high_import' and provide the following values
  #
  #     slack: {enabled: true, token: readstring('/run/secrets/slack'), channel: 'ctxd'}
  #
  alerts_high:
    content: |
      {
        console: {enabled: true},
        slack:   {enabled: false},
        mqtt:    {enabled: false},
      }

  # Thingsboard (Metrics)
  thingsboard_high:
    content: |
      {enabled: false, host: null, port: null, protocol:http}

  # Pipeline Telemetry
  #
  # If enabling pipeline telemetry to be sent to thingsboard you must also
  # uncomment the thingsboard entries in 'secrets' and 'services.high_import' 
  # and provide the following values
  #  
  #    thingsboard: {
  #      enabled: true, 
  #      host: "thingsboard.cloud", 
  #      protocol: https, 
  #      port: 443, 
  #      token: readstring('/run/secrets/thingsboard')
  #    }
  #
  stats_high:
    content: |
      {
        thingsboard: {enabled: false}
      }

#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    
#  slack:
#    file: ../../secrets/high/slack    

#
# List of Dockers
#
services:

  high_import:
    extends:
      file: ./ctxd.yml
      service: high_import
    hostname: import.high.zone2.ctxd  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs  
    volumes:
      - ../../volumes/zone2/high/import/certs:/opt/ct/certs
        
  high_export:
    extends:
      file: ./ctxd.yml
      service: high_export
    hostname: export.high.zone2.ctxd  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs
    volumes:
      - ../../volumes/zone2/high/export/certs:/opt/ct/certs
      - ../../volumes/zone2/high/export/keys:/opt/ct/keys
      - ../../volumes/high/export/git.sfjs:/opt/ct/integrations/git.sfjs
      - ../../volumes/high/export/signingPolicy.sfjs:/opt/ct/config/signingPolicy.sfjs
     
  high_mqtt:
    extends: 
      file: ./ctxd.yml
      service: high_mqtt
    hostname: mqtt.high.zone2.ctxd  
    ports: !override
      - 32883:1883
    volumes:
      - ../../volumes/zone2/high/mqtt/certs:/opt/ct/certs
 
  
networks:
  ctxd_high:
    name: ctxd_high_2
  ctxd_ops:
    name: ctxd_ops
    
