name: "ctxd-1"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
include:
  - ./config-zone1.yml
  
#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    

#
# List of Dockers
#
services:

  high_import:
    image:  ghcr.io/configuredthings/ctxd_high_import:${ctxd_version}
    hostname: import.high.zone1.ctxd  
    networks:
      ctxd_high:
        aliases:
           - status.high.zone1.ctxd
      ctxd_ops:    
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs
      - source: mqtt_high
        target: /opt/ct/integrations/mqtt.sfjs  
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: import_high 
        target: /opt/ct/config/import.sfjs
      - source: config_high
        target: /opt/ct/init-config/high-config-local.sfjs      
    volumes:
      - ../../volumes/zone1/high/import/certs:/opt/ct/certs
          
  high_export:
    image:  ghcr.io/configuredthings/ctxd_high_export:${ctxd_version}
    hostname: export.high.zone1.ctxd  
    networks:
      ctxd_high:
        aliases:
          - config.high.zone1.ctxd
      ctxd_ops:    
    secrets:
      - git  
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: gateway_high 
        target: /opt/ct/config/gateway.sfjs
      - source: import_high 
        target: /opt/ct/config/import.sfjs    
    volumes:
      - ../../volumes/zone1/high/export/certs:/opt/ct/certs
      - ../../volumes/zone1/high/export/keys:/opt/ct/keys
      - ../../volumes/zone1/high/export/git.sfjs:/opt/ct/integrations/git.sfjs
      - ../../volumes/zone1/high/export/signingPolicy.sfjs:/opt/ct/config/signingPolicy.sfjs
     
  high_mqtt:
    image:  ghcr.io/configuredthings/ctxd_high_mqtt:${ctxd_version}
    hostname: mqtt.high.zone1.ctxd
    ports:
      - 31883:1883
    networks:
      ctxd_high:
        aliases:
          - mqtt.high.zone1.ctxd
      ctxd_ops:    
    configs:
      - source: status_ops
        target: /opt/ct/system/config/status.sfjs
    volumes:
      - ../../volumes/zone1/high/mqtt/certs:/opt/ct/certs

networks:
  ctxd_high:
    name: ctxd_high_1
  ctxd_ops:
    name: ctxd_ops
    
