name: "ctxd-1"

#
# Docker Compose file for a development version of 
# the Cross Domain services in "Mono" mode using
# local images
#
include:
  - ./config-zone2.yml
  
#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    

#
# List of Dockers
#
services:

  high_import:
    image:  ghcr.io/configuredthings/ctxd_high:${ctxd_version}
    hostname: import.high.zone2.ctxd
    environment:
      - CT_INIT_DIR=/opt/ct/init/import     
    networks:
      ctxd_high:
        aliases:
           - status.high.zone2.ctxd
      ctxd_ops:    
    configs:
      - source: mqtt_high
        target: /opt/ct/integrations/mqtt.sfjs  
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: import_high 
        target: /opt/ct/config/import.sfjs
      - source: config_high
        target: /opt/ct/config/config.sfjs      
    volumes:
      - ../../volumes/zone2/high/import/certs:/opt/ct/certs
          
  high_export:
    image:  ghcr.io/configuredthings/ctxd_high:${ctxd_version}
    hostname: export.high.zone2.ctxd
    environment:
      - CT_INIT_DIR=/opt/ct/init/export      
    networks:
      ctxd_high:
        aliases:
          - config.high.zone2.ctxd
      ctxd_ops:    
    secrets:
      - git  
    configs:
      - source: zone
        target: /opt/ct/config/zone.sfjs
      - source: gateway_high 
        target: /opt/ct/config/gateway.sfjs
      - source: import_high 
        target: /opt/ct/config/import.sfjs    
    volumes:
      - ../../volumes/zone2/high/export/certs:/opt/ct/certs
      - ../../volumes/zone2/high/export/keys:/opt/ct/keys
      - ../../volumes/zone2/high/export/git.sfjs:/opt/ct/config/git.sfjs
      - ../../volumes/zone2/high/export/signingPolicy.sfjs:/opt/ct/config/signingPolicy.sfjs
     
  high_mqtt:
    image:  eclipse-mosquitto:alpine
    hostname: mqtt.high.zone2.ctxd
    ports:
      - 32883:1883
    networks:
      - ctxd_high
    configs:
      - source: mosquitto_high
        target: /mosquitto/config/mosquitto.conf 

networks:
  ctxd_high:
    name: ctxd_high_1
  ctxd_ops:
    name: ctxd_ops
    
