#
# Docker Compose file for a "mono" version of the
# Cross Domain services, which run without a hardsec
# Gateway.  
#
# This combines the services in
#   docker-compose-low-ctxd.yml
#   docker-compose-gateway.yml
#   docker-compose-high-ctxd.yml
#

name: "ctxd"

include:
  - ../high/config.yml
  - ../gateway/config.yml
  - ../low/config.yml
  - ../low/emulators_config.yml
     
#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    
  slack:
    file: ../../secrets/high/slack    

 
#
# List of Dockers
#
services:
  #
  # High Domain
  #
  high_import:
    extends: 
      file: ../high/ctxd.yml
      service: high_import  
    
  high_export:
    extends: 
      file: ../high/ctxd.yml
      service: high_export

  high_mqtt:
    extends: 
      file: ../high/ctxd.yml
      service: high_mqtt
      
  
  #
  # Gateway
  #
  import_diode:
    extends: 
      file: ../gateway/gateway.yml
      service: import_diode
  
  export_diode:
    extends: 
      file: ../gateway/gateway.yml
      service: export_diode
  
  #
  # Low Domain
  #
  low_import:
    extends: 
      file: ../low/ctxd.yml
      service: low_import
    
  low_export:
    extends: 
      file: ../low/ctxd.yml
      service: low_export
  
  low_mqtt:
    extends: 
      file: ../low/ctxd.yml
      service: low_mqtt
        
  low_emulators:
    extends: 
      file: ../low/emulators.yml
      service: low_emulators
  
networks:
  ctxd_ops:
    name: ctxd_ops
  ctxd_high:
    name: ctxd_high
  ctxd_low:
    name: ctxd_low
 



