#
# Docker Compose file for a "mono" version of the
# Cross Domain services, which run without a hardsec
# Gateway.  
#
# This combines the services in
#   docker-compose-low-ctxd.yml
#   docker-compose-gateway.yml
#   docker-compose-high-ctxd.yml
#

name: "ctxd"

configs:

  # High side of the Gateway (i.e. to Low domain)
  gateway_high:
    content: |
      {
        host: "gateway.high.ctxd",
        port: 80,
        protocol: http,
      }

  # High Side Import Web Server
  import_high:
    content: |
      {
        host: "import.high.ctxd",
        port: 80,
        protocol: http,
      }

  # Low Side Export Web Server
  export_high:
    content: |
      {
        host: "export.high.ctxd",
        port: 80,
        protocol: http,
      }
    
  # High Side Import Status Server
  status_high:
    content: |
      {
        remote: {
          host: "import.high.ctxd", 
          port: 7776, 
          channel: "ct-status"
        }
      }

  # External High Side MQTT server
  mqtt_high:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.high.ctxd",
          port:     1883,
          format:   json
      }

  # Alert targets    
  alerts_high:
    content: |
      {
        console: {enabled: true},
        slack:   {enabled: false},
        mqtt:    {enabled: false},
      }

  # Thingsboard (Metrics)
  thingsboard_high:
    content: |
        {enabled: false, host: null, port: null, protocol: http}

  # Pipeline Telemetry
  stats_high:
    content: |
      {
        thingsboard: {enabled: false}
      }    

  # Low side of the Gateway (i.e. to High domain)
  gateway_low:
    content: |
      {
        host: "gateway.low.ctxd",
        port: 80,
        protocol: http,
      }

  
  # External Low Side MQTT server
  mqtt_low:
    content: |
      {
          enabled:  true,
          protocol: mqtt,
          host:     "mqtt.low.ctxd",
          port:     1883,
          format:   json
      }

  # Low Side Export Web Server
  export_low:
    content: |
      {
        host: "export.low.ctxd",
        port: 80,
        protocol: http,
      }

  # Import Diode Config
  import_diode:
    content: |
      {  
        input:  {host: 'gateway.low.ctxd'},
        routes: {
          default: 'http://import.high.ctxd:80/files'
        }
      }

  # Export Diode Config
  export_diode:
    content: |
      {  
        input:  {host: 'gateway.high.ctxd'},
        routes: {
          default: 'http://export.low.ctxd:80/files'
        }
      }

#
# Secrets
#
secrets:
  git:
    file: ../../secrets/high/git    
  slack:
    file: ../../secrets/high/slack    

  
#
# List of Dockers
#
services:
  #
  # High Domain
  #
  high_import:
    extends: 
      file: ../high/ctxd.yml
      service: high_import  
    
  high_export:
    extends: 
      file: ../high/ctxd.yml
      service: high_export

  high_mqtt:
    extends: 
      file: ../high/ctxd.yml
      service: high_mqtt
      
  
  #
  # Gateway
  #
  import_diode:
    extends: 
      file: ../gateway/gateway.yml
      service: import_diode
  
  export_diode:
    extends: 
      file: ../gateway/gateway.yml
      service: export_diode
  
  #
  # Low Domain
  #
  low_import:
    extends: 
      file: ../low/ctxd.yml
      service: low_import
    
  low_export:
    extends: 
      file: ../low/ctxd.yml
      service: low_export
  
  low_mqtt:
    extends: 
      file: ../low/ctxd.yml
      service: low_mqtt
        
  low_emulators:
    extends: 
      file: ../low/ctxd.yml
      service: low_emulators
  
networks:
  ctxd_ops:
    name: ctxd_ops
  ctxd_high:
    name: ctxd_high
  ctxd_low:
    name: ctxd_low
 



