#
# Docker Compose file for the Status and Console Components
#   
#
name: ctxd-ops

configs:
  # Config details for an external git webhook server  
  ext_webhook:
    content: |
      {
        host: "gwhg.service.trade.configuredthings.com",
      }

secrets:
  git:
    file: ../../secrets/ops/console/ct-admin/git    
  user:
    file: ../../secrets/ops/console/ct-admin/password

services:

  status:
    extends: 
      file: ./ops-local.yml
      service: status
    volumes:
      - ${XD_DEV?}/node_modules:/opt/ct/node_modules
    
  console:
    extends: 
      file: ./ops-local.yml
      service: console
  
networks:
  ctxd_ops:
    name: ctxd_ops


