#
# Docker Compose file for the Status and Console Components
#   
#
name: ctxd-ops

secrets:
  git:
    file: ../../secrets/ops/console/ct-admin/git    
  user:
    file: ../../secrets/ops/console/ct-admin/password

services:

  status:
    extends: 
      file: ../ops/ops.yml
      service: status
    image: ctxd_ops_status:3.3.0

  console:
    extends: 
      file: ../ops/ops.yml
      service: console
    image: sfjs-console:3.1.0
  
networks:
  ctxd_ops:
    name: ctxd_ops

